name: 🚀 Windows RDP (Manual Run)

on:
  workflow_dispatch: # فقط اجرای دستی

jobs:
  windows-rdp:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 ساعت

    steps:
    - name: 🔻 Checkout repository
      uses: actions/checkout@v4

    - name: ⬇️ Download cloudflared
      run: |
        Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe" -OutFile "cloudflared.exe"

    - name: 🛠️ Configure RDP Settings
      run: |
        # فعال کردن RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # تنظیم رمز عبور برای کاربر runner
        $password = ConvertTo-SecureString "YourStrongPassword123!" -AsPlainText -Force
        Set-LocalUser -Name "runner" -Password $password
        Write-Output "✔️ RDP configured successfully"

    - name: 🔐 Setup Cloudflare Tunnel
      env:
        TUNNEL_CREDENTIALS: ${{ secrets.CLOUDFLARE_TUNNEL_CREDENTIALS }}
        TUNNEL_ID: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
      run: |
        # ایجاد پوشه تنظیمات
        New-Item -ItemType Directory -Path "$env:USERPROFILE\.cloudflared" -Force
        
        # ذخیره credentials
        [IO.File]::WriteAllText("$env:USERPROFILE\.cloudflared\credentials.json", $env:TUNNEL_CREDENTIALS)
        
        # ایجاد فایل config
        $config = @"
tunnel: $env:TUNNEL_ID
credentials-file: $env:USERPROFILE\.cloudflared\credentials.json
ingress:
  - hostname: win.net2ray.dpdns.org
    service: rdp://localhost:3389
  - service: http_status:404
"@
        [IO.File]::WriteAllText("$env:USERPROFILE\.cloudflared\config.yml", $config)
        Write-Output "✔️ Cloudflare Tunnel configured"

    - name: 🚀 Run Cloudflare Tunnel
      run: Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "tunnel run" -WindowStyle Hidden
      continue-on-error: true

    - name: ℹ️ Display Connection Info
      run: |
        Write-Output "✅ RDP Server is ready!"
        Write-Output "▸ Connect to: win.net2ray.dpdns.org"
        Write-Output "▸ Username: runner"
        Write-Output "▸ Password: YourStrongPassword123!"
        Write-Output "▸ This session will auto-terminate after 6 hours"
