name: Auto Node Conversion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests
        
    - name: Run conversion
      run: |
        python main.py
        
    - name: Commit and push
      run: |
        # بررسی وجود محتوای معتبر
        if [ -s "output.txt" ]; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output.txt
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No valid output to commit"
          # آپلود اسکرین‌شات خطا برای دیباگ
          if [ -f "error.png" ]; then
            echo "Uploading error screenshot..."
            # اینجا می‌توانید آپلود به جای خاصی را اضافه کنید
          fi
          exit 0  # خروج بدون خطا
        fi
