name: Auto Node Conversion

on:
  workflow_dispatch:  # این خط باید وجود داشته باشد
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests
        
- name: Run conversion
  run: |
    sudo apt-get update
    sudo apt-get install -y chromium-browser chromium-chromedriver
    python -m pip install --upgrade pip
    pip install selenium webdriver-manager requests
    python main.py
         
    - name: Commit and push result
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add output.txt
        git commit -m "Updated converted nodes"
        git push
