name: Config Generator

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  generate-configs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pybase64
        
    - name: Fetch and convert configs
      run: |
        python scripts/fetch_configs.py
        python scripts/convert_to_json.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions@example.com"
        git config --local user.name "GitHub Actions"
        git add outputs/
        git commit -m "Auto-update configs $(date +'%Y-%m-%d')"
        git push
