name: Config Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-configs:
    runs-on: ubuntu-latest
    
    # Add this permissions block
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Important for git history
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pybase64
        
    - name: Fetch and convert configs
      run: |
        python scripts/fetch_configs.py
        python scripts/convert_to_json.py
        ls -l raw_configs/  # List downloaded files
        ls -l outputs/     # List generated files
        
    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add outputs/
        git status  # Show status before commit
        git commit -m "Auto-update configs $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
