- name: Fetch and convert configs
  run: |
    # Debug information
    echo "Current directory:"
    pwd
    echo "Directory contents:"
    ls -la
    echo "Inputs directory:"
    ls -la inputs/
    
    # Run scripts with verbose output
    python scripts/fetch_configs.py
    echo "Raw configs downloaded:"
    ls -la raw_configs/
    
    python scripts/convert_for_hiddify.py
    echo "Outputs generated:"
    ls -la outputs/
    
    # Verify outputs are not empty
    if [ -z "$(ls -A outputs/)" ]; then
      echo "Error: No output files generated!"
      exit 1
    fi 
