name: Hiddify Config Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pybase64
        
    - name: Clone Hiddify-core
      run: git clone https://github.com/hiddify/hiddify-core.git
        
    - name: Fetch and convert configs
      run: |
        python scripts/fetch_configs.py
        python scripts/convert_for_hiddify.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add outputs/
        git commit -m "Auto-update Hiddify configs $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
