name: Convert Config Daily

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز در نیمه شب اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Install subconverter using official script
        run: |
          curl -sSL https://raw.githubusercontent.com/lonelam/subconverter-rs/main/scripts/setup_and_run_subconverter.sh | bash
          echo "$HOME/subconverter" >> $GITHUB_PATH

      - name: Download source config
        run: |
          curl -s -o input.json https://raw.githubusercontent.com/e-schamberger/free/refs/heads/main/config/vless.json

      - name: Convert to sing-box
        run: |
          subconverter input.json -t sing-box -o singbox.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add singbox.json
          git commit -m "Update singbox config [skip ci]" || echo "No changes to commit"
          git push
