name: Convert Config Daily

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز در نیمه شب اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract subconverter
        run: |
          wget https://github.com/lonelam/subconverter-rs/releases/download/v0.2.33/subconverter-linux-amd64-0.2.33.tar.gz
          tar -xzf subconverter-linux-amd64-0.2.33.tar.gz
          chmod +x subconverter

      - name: Download source config
        run: |
          curl -s -o input.json https://raw.githubusercontent.com/e-schamberger/free/refs/heads/main/config/vless.json

      - name: Convert to sing-box
        run: |
          ./subconverter input.json -t sing-box -o singbox.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add singbox.json
          git commit -m "Update singbox config [skip ci]" || echo "No changes to commit"
          git push
