name: Node Conversion
on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run conversion script
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\scripts\convert-node.ps1
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: automation-results
        path: |
          ${{ github.workspace }}/converted-node.txt
          ${{ runner.temp }}/selenium_error_*.png
        
    - name: Commit result
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add converted-node.txt
        git diff-index --quiet HEAD || git commit -m "Add converted node"
        git push
