name: Convert Config Daily

on:
  schedule:
    - cron: '0 0 * * *'  # هر روز در نیمه شب اجرا می‌شود
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install subconverter-rs
        run: cargo install --git https://github.com/lonelam/subconverter-rs

      - name: Download source config
        run: |
          curl -s -o input.json https://raw.githubusercontent.com/e-schamberger/free/refs/heads/main/config/vless.json

      - name: Convert to sing-box
        run: |
          subconverter input.json -t sing-box -o singbox.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add singbox.json
          git commit -m "Update singbox config [skip ci]" || echo "No changes to commit"
          git push
