name: Hiddify Windows Setup

on:
  workflow_dispatch:

jobs:
  hiddify-setup:
    runs-on: windows-latest

    steps:
    - name: Download Hiddify Portable
      run: |
        $url = "https://github.com/hiddify/hiddify-app/releases/download/v2.0.5/Hiddify-Windows-Portable-x64.zip"
        $output = "Hiddify-Windows-Portable-x64.zip"
        Invoke-WebRequest -Uri $url -OutFile $output

    - name: Extract Files
      run: |
        Expand-Archive -Path "Hiddify-Windows-Portable-x64.zip" -DestinationPath .

    - name: Set clipboard content (اضافه کردن کانفیگ به کلیپبورد)
      run: |
        # محتوای کانفیگ خود را اینجا قرار دهید
        $configContent = @"
        {
          "config": "محتویات کانفیگ شما اینجا قرار میگیرد"
        }
        "@
        Set-Clipboard -Value $configContent

    - name: Create automation script
      run: |
        @"
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName Microsoft.VisualBasic

        # Start Hiddify
        Start-Process "Hiddify.exe" -PassThru
        Start-Sleep -Seconds 10  # افزایش زمان انتظار

        # Click 'Start' button
        [Microsoft.VisualBasic.Interaction]::AppActivate("Hiddify")
        [System.Windows.Forms.SendKeys]::SendWait("{TAB 5}")  # 5 بار تب
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
        Start-Sleep -Seconds 5

        # Click '+' button
        [System.Windows.Forms.SendKeys]::SendWait("%{TAB}")   # Alt+Tab برای فوکوس
        [System.Windows.Forms.SendKeys]::SendWait("{TAB 10}") # 10 بار تب
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
        Start-Sleep -Seconds 3

        # Select 'Add from clipboard'
        [System.Windows.Forms.SendKeys]::SendWait("{DOWN 4}") # 4 بار پایین
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
        Start-Sleep -Seconds 10  # افزایش زمان برای ذخیره فایل

        # Close application
        Get-Process -Name "Hiddify" | Stop-Process -Force
        "@ | Out-File -FilePath "automation.ps1" -Encoding UTF8

    - name: Run Hiddify with automation
      run: |
        powershell -ExecutionPolicy Bypass -File "automation.ps1"

    - name: Save config file
      run: |
        $configPath = "$env:APPDATA\Hiddify\hiddify\configs"
        $dest = "hiddify-config"
        New-Item -ItemType Directory -Path $dest -Force
        Get-ChildItem -Path $configPath | Copy-Item -Destination $dest -Force

    - name: Upload config to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: hiddify-config
        path: hiddify-config/
