name: Hiddify Windows Setup with RDP Access

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest

    steps:
    # مرحله 1: دانلود و استخراج Hiddify
    - name: Download Hiddify Portable
      run: |
        $url = "https://github.com/hiddify/hiddify-app/releases/download/v2.0.5/Hiddify-Windows-Portable-x64.zip"
        $output = "Hiddify-Windows-Portable-x64.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        
    - name: Extract Hiddify Files
      run: |
        Expand-Archive -Path "Hiddify-Windows-Portable-x64.zip" -DestinationPath .
        
    # مرحله 2: تنظیم اتوماسیون اجرای Hiddify
    - name: Set clipboard content
      run: |
        $configUrl = "https://raw.githubusercontent.com/e-schamberger/free/refs/heads/main/config/vless.json"
        Set-Clipboard -Value $configUrl
        
    - name: Create automation script
      run: |
        @'
        Add-Type -AssemblyName System.Windows.Forms
        Add-Type -AssemblyName Microsoft.VisualBasic

        # Start Hiddify
        $process = Start-Process "Hiddify.exe" -PassThru
        Start-Sleep -Seconds 30

        # Click 'Start' button
        [Microsoft.VisualBasic.Interaction]::AppActivate($process.Id)
        Start-Sleep -Seconds 5
        [System.Windows.Forms.SendKeys]::SendWait("{TAB 5}")
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
        Start-Sleep -Seconds 15

        # Click '+' button
        [System.Windows.Forms.SendKeys]::SendWait("%{TAB}")
        Start-Sleep -Seconds 2
        [System.Windows.Forms.SendKeys]::SendWait("{TAB 10}")
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
        Start-Sleep -Seconds 10

        # Select 'Add from clipboard'
        [System.Windows.Forms.SendKeys]::SendWait("{DOWN 4}")
        [System.Windows.Forms.SendKeys]::SendWait("{ENTER}")
        Start-Sleep -Seconds 60  # Wait for download

        # Close application
        $process | Stop-Process -Force
        '@ | Out-File -FilePath "automation.ps1" -Encoding UTF8
        
    - name: Run Hiddify with automation
      run: |
        powershell -ExecutionPolicy Bypass -File "automation.ps1"
        
    # مرحله 3: فعال‌سازی RDP (همان کدی که شما ارائه دادید)
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        
    - name: Extract ngrok
      run: |
        Expand-Archive ngrok.zip -DestinationPath ngrok
        
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        
    - name: Set password for runneradmin
      run: |
        $password = ConvertTo-SecureString -String "Shahid@123" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $password
        
    # مرحله 4: ایجاد تونل ngrok (آخرین مرحله)
    - name: Create ngrok tunnel
      run: Start-Process -NoNewWindow -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389"
