name: GUI with Localtonet
on: workflow_dispatch

jobs:
  gui-access:
    runs-on: ubuntu-latest
    steps:
      - name: Install GUI and VNC
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver
          mkdir -p ~/.vnc
          echo -e "123456\n123456\nn" | vncpasswd
          vncserver :1 -geometry 1280x800 -localhost

      - name: Download Localtonet (alternative)
         run: |
           wget https://cdn.localtonet.com/static/localtunnel/latest/linux -O localtonet || wget https://github.com/portmapper-io/localtonet/releases/download/v1.0.0/localtonet_linux -O localtonet
           chmod +x localtonet
