name: Windows Remote Access via PageKite
on: 
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: windows-latest
    timeout-minutes: 360  # 6 ساعت
    steps:
    - name: Setup PageKite
      run: |
        # Download PageKite
        Invoke-WebRequest -Uri "https://pagekite.net/pk/pagekite.py" -OutFile "pagekite.py"
        
        # Start PageKite for SSH (2222) and RDP (3389)
        Start-Process python -ArgumentList "pagekite.py --clean --frontend=pagekite.net 2222 ${{ secrets.PAGEKITE_USERNAME }}.pagekite.me:${{ secrets.PAGEKITE_SECRET }}" -NoNewWindow
        Start-Process python -ArgumentList "pagekite.py --clean --frontend=pagekite.net 3389 ${{ secrets.PAGEKITE_USERNAME }}-rdp.pagekite.me:${{ secrets.PAGEKITE_SECRET }}" -NoNewWindow
        
        # Enable RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Set password for runner user
        $password = ConvertTo-SecureString "YourStrongPass123!" -AsPlainText -Force
        Set-LocalUser -Name "runner" -Password $password
        
        # Wait for 6 hours
        Start-Sleep -Seconds 21600
      shell: powershell
