name: Windows Remote Access via PageKite
on: 
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setup Remote Access
      run: |
        # ایجاد کاربر جدید یا استفاده از کاربر موجود
        $securePassword = ConvertTo-SecureString "YourStrongPass123!" -AsPlainText -Force
        try {
            Set-LocalUser -Name "runneradmin" -Password $securePassword -ErrorAction Stop
            $username = "runneradmin"
        } catch {
            New-LocalUser -Name "remoteuser" -Password $securePassword
            Add-LocalGroupMember -Group "Administrators" -Member "remoteuser"
            $username = "remoteuser"
        }

        # فعال کردن RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        # دانلود و تنظیم PageKite
        Invoke-WebRequest -Uri "https://pagekite.net/pk/pagekite.py" -OutFile "pagekite.py"
        Start-Process python -ArgumentList "pagekite.py --clean --frontend=pagekite.net 3389 ${{ secrets.PAGEKITE_USERNAME }}-rdp.pagekite.me:${{ secrets.PAGEKITE_SECRET }}" -NoNewWindow
        
        # انتظار برای 6 ساعت
        Start-Sleep -Seconds 21600
      shell: powershell
