name: Windows Remote Server via PageKite
on: 
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setup Remote Access
      run: |
        # تنظیمات اولیه
        $ErrorActionPreference = "Stop"
        
        # 1. ایجاد کاربر
        $username = "remoteadmin"
        $password = "SecurePass123!"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        
        try {
            New-LocalUser -Name $username -Password $securePassword -ErrorAction SilentlyContinue
            Add-LocalGroupMember -Group "Administrators" -Member $username
            Write-Host "User created successfully"
        } catch {
            Set-LocalUser -Name $username -Password $securePassword
            Write-Host "User password updated"
        }

        # 2. فعال کردن RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Write-Host "RDP enabled"

        # 3. تنظیمات PageKite
        Invoke-WebRequest -Uri "https://pagekite.net/pk/pagekite.py" -OutFile "pagekite.py"
        
        # فرمت صحیح دستور PageKite
        $kite_name = "${{ secrets.PAGEKITE_USERNAME }}-rdp.pagekite.me"
        $kite_secret = "${{ secrets.PAGEKITE_SECRET }}"
        
        # دستور اصلاح شده با فرمت صحیح
        $command = "--clean --frontend=pagekite.net --service_on=raw:${kite_name}:localhost:3389:$kite_secret"
        
        Write-Host "Executing: python pagekite.py $command"
        Start-Process python -ArgumentList "pagekite.py", "--clean", "--frontend=pagekite.net", "--service_on=raw:${kite_name}:localhost:3389:$kite_secret" -NoNewWindow
        
        # 4. نمایش اطلاعات اتصال
        Write-Host "`n=== CONNECTION DETAILS ==="
        Write-Host "RDP Address: $kite_name"
        Write-Host "Username: $username"
        Write-Host "Password: $password"
        Write-Host "=========================`n"
        
        # 5. نگه داشتن session فعال
        Write-Host "Server will remain active for 6 hours..."
        Start-Sleep -Seconds 21600
      shell: powershell
