name: Stable VNC Connection
on: workflow_dispatch

jobs:
  vnc-connection:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 ساعت

    steps:
    - name: Install and configure VNC
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies tightvncserver
        
        # تنظیم رمز عبور امن
        mkdir -p ~/.vnc
        echo -e "MySecurePass123!\nMySecurePass123!\nn" | vncpasswd
        
        # تنظیمات بهینه برای اتصال پایدار
        cat > ~/.vnc/xstartup <<EOL
        #!/bin/sh
        unset SESSION_MANAGER
        exec /bin/sh /etc/X11/xinit/xinitrc
        [ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
        [ -r \$HOME/.Xresources ] && xrdb \$HOME/.Xresources
        xsetroot -solid grey
        export XKL_XMODMAP_DISABLE=1
        exec startxfce4
        EOL
        
        chmod +x ~/.vnc/xstartup
        vncserver :1 -geometry 1280x800 -depth 24 -localhost

    - name: Establish stable tunnel
      run: |
        sudo apt install -y autossh
        
        # ایجاد تونل با کنترل بهتر
        autossh -M 0 -f -N \
          -o "ServerAliveInterval 30" \
          -o "ServerAliveCountMax 3" \
          -o "ExitOnForwardFailure=yes" \
          -R vnc-$(date +%s).serveo.net:80:localhost:5901 serveo.net
        
        # مانیتورینگ وضعیت اتصال
        while true; do
          if ! pgrep -x "Xtightvnc" >/dev/null; then
            echo "VNC server crashed! Restarting..."
            vncserver :1 -geometry 1280x800 -depth 24 -localhost
          fi
          
          if ! pgrep -x "autossh" >/dev/null; then
            echo "Tunnel connection lost! Reconnecting..."
            autossh -M 0 -f -N \
              -o "ServerAliveInterval 30" \
              -o "ServerAliveCountMax 3" \
              -o "ExitOnForwardFailure=yes" \
              -R vnc-$(date +%s).serveo.net:80:localhost:5901 serveo.net
          fi
          
          sleep 30
          echo "$(date): Connection check passed"
        done
