name: VNC with Serveo (Complete Info)
on: workflow_dispatch

jobs:
  vnc-session:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 ساعت

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y xfce4 tightvncserver autossh curl jq

    - name: Set up VNC
      run: |
        # تنظیم رمز عبور
        mkdir -p ~/.vnc
        VNC_PASSWORD="MySecurePass$(date +%s | cut -c 6-10)"
        echo -e "$VNC_PASSWORD\n$VNC_PASSWORD\nn" | vncpasswd
        
        # راه اندازی VNC Server
        vncserver :1 -geometry 1280x800 -localhost
        
        # ذخیره اطلاعات در env
        echo "VNC_PASSWORD=$VNC_PASSWORD" >> $GITHUB_ENV
        echo "VNC_PORT=5901" >> $GITHUB_ENV

    - name: Start Serveo tunnel
      run: |
        # تولید آدرس تصادفی
        SUBDOMAIN="vnc-$(openssl rand -hex 3)"
        
        # راه اندازی تونل
        autossh -M 0 -f -N \
          -o "ExitOnForwardFailure=yes" \
          -R $SUBDOMAIN.serveo.net:80:localhost:${{ env.VNC_PORT }} serveo.net
        
        # دریافت آدرس عمومی
        sleep 5
        PUBLIC_URL=$(curl -s http://serveo.net/api/tunnels | jq -r '.tunnels[0].public_url')
        
        # نمایش اطلاعات اتصال
        echo "=========================================="
        echo "VNC Connection Details:"
        echo "Address: $PUBLIC_URL"
        echo "Port: ${{ env.VNC_PORT }}"
        echo "Password: ${{ env.VNC_PASSWORD }}"
        echo "=========================================="
        
        # ذخیره اطلاعات در خروجی
        echo "VNC_ADDRESS=$PUBLIC_URL" >> $GITHUB_ENV

    - name: Keep connection alive
      run: |
        while true; do
          echo "$(date): VNC Session is active"
          echo "Connection Info:"
          echo "Address: ${{ env.VNC_ADDRESS }}"
          echo "Password: ${{ env.VNC_PASSWORD }}"
          sleep 60
        done
