name: VNC with Serveo
on: workflow_dispatch

jobs:
  vnc-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y xfce4 tightvncserver autossh curl

    - name: Set up VNC password
      run: |
        mkdir -p ~/.vnc
        echo -e "123456\n123456\nn" | vncpasswd
        vncserver :1 -geometry 1280x800 -localhost

    - name: Start Serveo tunnel and get URL
      run: |
        # Generate random subdomain
        SUBDOMAIN="vnc-$(date +%s)"
        
        # Start autossh in background
        autossh -M 0 -f -N -R $SUBDOMAIN.serveo.net:80:localhost:5901 serveo.net
        
        # Wait for connection
        sleep 5
        
        # Get public URL
        echo "VNC Address: $SUBDOMAIN.serveo.net:5901"
        echo "VNC Password: 123456"
        
        # Keep checking connection
        while true; do
          if ! pgrep -x "autossh" > /dev/null; then
            echo "Connection lost! Reconnecting..."
            autossh -M 0 -f -N -R $SUBDOMAIN.serveo.net:80:localhost:5901 serveo.net
          fi
          sleep 60
        done
